package com.order.orderservice.dto;

import com.order.orderservice.enums.OrderStatus;
import com.order.orderservice.enums.PaymentStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderResponse {

    // ==========================================================
    // Unique Order ID (Primary Key)
    // Auto Generated by Database
    // ==========================================================
    private Long id;


    // ==========================================================
    // Unique Order Number
    // Example : ORD-1001
    // ==========================================================
    private String orderNumber;


    // ==========================================================
    // Customer ID
    // ==========================================================
    private Long customerId;


    // ==========================================================
    // Product ID
    // ==========================================================
    private Long productId;


    // ==========================================================
    // Ordered Quantity
    // ==========================================================
    private Integer quantity;


    // ==========================================================
    // Product Price
    // ==========================================================
    private Double price;


    // ==========================================================
    // Total Order Amount
    // ==========================================================
    private Double totalAmount;


    // ==========================================================
    // Current Order Status
    // Example :
    // PENDING
    // CONFIRMED
    // PROCESSING
    // SHIPPED
    // DELIVERED
    // CANCELLED
    // RETURNED
    // ==========================================================
    private OrderStatus orderStatus;


    // ==========================================================
    // Current Payment Status
    // Example :
    // PENDING
    // PAID
    // FAILED
    // REFUNDED
    // CANCELLED
    // ==========================================================
    private PaymentStatus paymentStatus;


    // ==========================================================
    // Order Date & Time
    // ==========================================================
    private LocalDateTime orderDate;


    // ==========================================================
    // Record Created Date & Time
    // Automatically Set While Creating Order
    // ==========================================================
    private LocalDateTime createdDate;


    // ==========================================================
    // Record Last Updated Date & Time
    // Automatically Updated Whenever Order Changes
    // ==========================================================
    private LocalDateTime updatedDate;

}




































































/*
package com.order.orderservice.dto;

import com.order.orderservice.enums.OrderStatus;
import com.order.orderservice.enums.PaymentStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderResponse {

    private Long id;

    private String orderNumber;

    private Long customerId;

    private Long productId;

    private Integer quantity;

    private Double price;

    private Double totalAmount;

    private OrderStatus orderStatus;

    private PaymentStatus paymentStatus;

    private LocalDateTime orderDate;

    private LocalDateTime createdDate;

    private LocalDateTime updatedDate;

}*/
